### ISSUE TITLE
Some essential files are missing!

### ISSUE THREAD

**Issue by ltp1995** [sairin1202/Commonsense-Knowledge-Aware-Concept-Selection-For-Diverse-and-Informative-Visual-Storytelling#1]
Thanks for your excellent work! But some essential files are missing(_et al._  **data/train.pkl, data/test.pkl, data/clarifai/**), in addition, could you complete the README.md to give more detailed instructions about data processing, training and testing. Appreciate it if you could reply.

**Comment by ltp1995** [comment]
Got it, thanks for your kind reply!

**Comment by sujiaqi-1** [comment]
> Got it, thanks for your kind reply!

Hi,I also meet this problem,could you share the  data with me,Appreciate it if you could reply!
